# Generated by Django 4.0.6 on 2022-08-29 08:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default='2001-01-01')),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.IntegerField(choices=[(0, 'Select'), (1, 'Abia'), (2, 'Adamawa'), (3, 'Akwa Ibom'), (4, 'Anambra'), (5, 'Bauchi'), (6, 'Bayelsa'), (7, 'Benue'), (8, 'Borno'), (9, 'Cross River'), (10, 'Delta'), (11, 'Ebonyi'), (12, 'Edo'), (13, 'Ekiti'), (14, 'Enugu'), (15, 'Gombe'), (16, 'Imo'), (17, 'Jigawa'), (18, 'Kaduna'), (19, 'Kano'), (20, 'Katsina'), (21, 'Kebbi'), (22, 'Kogi'), (23, 'Kwara'), (24, 'Lagos'), (25, 'Nasarawa'), (26, 'Niger'), (27, 'Ogun'), (28, 'Ondo'), (29, 'Osun'), (30, 'Oyo'), (31, 'Plateau'), (32, 'Rivers'), (33, 'Sokoto'), (34, 'Taraba'), (35, 'Yobe'), (36, 'Zamfara'), (37, 'FCT')], default=0)),
                ('home_address', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
