# Generated by Django 4.0.6 on 2022-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='set_deadline',
            field=models.DateTimeField(help_text='Optional. Set Deadline For Your Task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.TextField(help_text='optional. Add A Short Description Of Your Task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(help_text='Enter Your Task Name', max_length=100),
        ),
    ]
