# Generated by Django 4.0.6 on 2022-08-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todo_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='set_deadline',
            field=models.DateTimeField(default='', help_text='Optional. Set Deadline For Your Task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.TextField(default='', help_text='Optional. Add A Short Description Of Your Task'),
        ),
    ]
