# Generated by Django 4.0.6 on 2022-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todo_set_deadline_alter_todo_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='set_deadline',
            field=models.DateField(help_text='Set Deadline For Your Task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.TextField(help_text='Add A Short Description Of Your Task'),
        ),
    ]
