# Generated by Django 4.0.6 on 2022-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_todo_set_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='set_deadline',
            field=models.DateField(blank=True, help_text='Optional. Set Deadline For Your Task In Format YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.TextField(blank=True, help_text='Optional. Add A Short Description Of Your Task', null=True),
        ),
    ]
