# Generated by Django 4.0.6 on 2022-08-30 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_todo_set_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='set_deadline',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
