# Generated by Django 4.0.6 on 2022-08-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_remove_todo_set_deadline_todo_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_of_birth',
            new_name='deadline',
        ),
    ]
