# Generated by Django 4.0.6 on 2022-08-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_rename_date_of_birth_todo_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
    ]
