# Generated by Django 4.0.6 on 2022-08-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_remove_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='mark_as_done',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
    ]
