# Generated by Django 4.0.6 on 2022-09-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0018_image3_image4_image5_image6_image7_image8_image9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image3',
            old_name='image2',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='image4',
            old_name='image2',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='image5',
            old_name='image2',
            new_name='image5',
        ),
        migrations.RenameField(
            model_name='image6',
            old_name='image2',
            new_name='image6',
        ),
        migrations.RenameField(
            model_name='image7',
            old_name='image2',
            new_name='image7',
        ),
        migrations.RenameField(
            model_name='image8',
            old_name='image2',
            new_name='image8',
        ),
        migrations.RenameField(
            model_name='image9',
            old_name='image2',
            new_name='image9',
        ),
    ]
