# Generated by Django 4.0.6 on 2022-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_rename_image2_image3_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.TextField(blank=True, help_text='Optional. Add A Short Description Of Your Task Or Deadline', null=True),
        ),
    ]
